{%- extends 'null.tpl' -%}

{% block header %}
# Generated by nuclio-jupyter exporter
{% endblock header %}

{% block in_prompt %}
{% endblock in_prompt %}

{% block input %}
{{ cell.source | nuclio }}
{% endblock input %}

{% block markdowncell scoped %}
{% endblock markdowncell %}
