
# Generated by nuclio-jupyter exporter

# In[1]:


def greeting(name):
    return 'Hi ' + name + '. How are you?'


# In[2]:


default_name = 'Dave'


# In[3]:




# In[4]:


def handler(context, event):
    # nuclio:handler
    return greeting(event.body)
